
USE ROLE ACCOUNTADMIN;
USE SECONDARY ROLES NONE;

-- ----------------------------------------
-- CUSTOM ROLE AND GRANTS

CREATE ROLE IF NOT EXISTS MONITORING_ASSESSMENT_ROLE COMMENT = 'Role for the monitoring assessment skill.';

GRANT ROLE MONITORING_ASSESSMENT_ROLE TO ROLE SYSADMIN;

GRANT IMPORTED PRIVILEGES ON DATABASE SNOWFLAKE TO ROLE MONITORING_ASSESSMENT_ROLE;
GRANT DATABASE ROLE SNOWFLAKE.GOVERNANCE_VIEWER TO ROLE MONITORING_ASSESSMENT_ROLE;
GRANT DATABASE ROLE SNOWFLAKE.SECURITY_VIEWER TO ROLE MONITORING_ASSESSMENT_ROLE;
GRANT DATABASE ROLE SNOWFLAKE.USAGE_VIEWER TO ROLE MONITORING_ASSESSMENT_ROLE;
GRANT MONITOR USAGE ON ACCOUNT TO ROLE MONITORING_ASSESSMENT_ROLE;
GRANT IMPORT SHARE ON ACCOUNT TO ROLE MONITORING_ASSESSMENT_ROLE;

-- ----------------------------------------
-- DEDICATED WAREHOUSE 

CREATE WAREHOUSE IF NOT EXISTS MONITORING_ASSESSMENT_WH
    WITH WAREHOUSE_SIZE = 'X-SMALL'
    AUTO_SUSPEND = 60
    AUTO_RESUME = TRUE
    INITIALLY_SUSPENDED = TRUE
    COMMENT = 'Warehouse dedicated to monitoring assessment';

GRANT USAGE ON WAREHOUSE MONITORING_ASSESSMENT_WH TO ROLE MONITORING_ASSESSMENT_ROLE;

-- ----------------------------------------
-- DATABASE AND SCHEMA 

USE ROLE SYSADMIN;
USE SECONDARY ROLES NONE;

CREATE DATABASE IF NOT EXISTS MONITORING_ASSESSMENT_DB COMMENT = 'Database for monitoring assessment objects.';
CREATE SCHEMA IF NOT EXISTS MONITORING_ASSESSMENT_DB.ASSESSMENT WITH MANAGED ACCESS;

GRANT ALL ON DATABASE MONITORING_ASSESSMENT_DB TO ROLE MONITORING_ASSESSMENT_ROLE;
GRANT ALL ON SCHEMA MONITORING_ASSESSMENT_DB.ASSESSMENT TO ROLE MONITORING_ASSESSMENT_ROLE;
