
USE ROLE MONITORING_ASSESSMENT_ROLE;
USE SECONDARY ROLES NONE;
USE WAREHOUSE MONITORING_ASSESSMENT_WH;

CREATE OR REPLACE VIEW MONITORING_ASSESSMENT_DB.ASSESSMENT.V_DOMAIN_ASSESSMENT AS
WITH SNOWFLAKE_METADATA_RESULT AS ( 
    SELECT
        *
    FROM 
        SNOWFLAKE.ACCOUNT_USAGE.QUERY_HISTORY
    WHERE 1=1 
        AND START_TIME >= DATEADD(DAY, -90, CURRENT_TIMESTAMP())
        AND QUERY_TYPE NOT IN ('SELECT','INSERT','UPDATE','DELETE','MERGE','SHOW','USE','DESCRIBE')
        AND EXECUTION_STATUS = 'SUCCESS'
        AND USER_NAME NOT IN ('SYSTEM')
        AND ROLE_NAME NOT IN ('SNOWFLAKE')
)

,SNOWFLAKE_METADATA_CLASSIFIED AS (
    SELECT 
        QUERY_ID,
        START_TIME,
        QUERY_TEXT,
        CASE 
            ------ IDENTIFIABLE THROUGH QUERY_TYPE ------
            -- USER
            WHEN QUERY_TYPE = 'CREATE_USER' THEN 'USER'
            WHEN QUERY_TYPE = 'ALTER_USER' THEN 'USER'
            WHEN QUERY_TYPE = 'DROP_USER' THEN 'USER'
            -- ROLE
            WHEN QUERY_TYPE = 'CREATE_ROLE' THEN 'ROLE'
            WHEN QUERY_TYPE = 'ALTER_ROLE' THEN 'ROLE'
            WHEN QUERY_TYPE = 'DROP_ROLE' THEN 'ROLE'
            -- GRANT AND REVOKE
            WHEN QUERY_TYPE = 'GRANT' THEN 'GRANT AND REVOKE'
            WHEN QUERY_TYPE = 'REVOKE' THEN 'GRANT AND REVOKE'
            -- NETWORK POLICY
            WHEN QUERY_TYPE = 'CREATE_NETWORK_POLICY' THEN 'NETWORK POLICY'
            WHEN QUERY_TYPE = 'ALTER_NETWORK_POLICY' THEN 'NETWORK POLICY'
            WHEN QUERY_TYPE = 'DROP_NETWORK_POLICY' THEN 'NETWORK POLICY'
            -- ROW ACCESS POLICY
            WHEN QUERY_TYPE = 'CREATE_ROW_ACCESS_POLICY' THEN 'ROW ACCESS POLICY'
            WHEN QUERY_TYPE = 'ALTER_TABLE_MANAGE_ROW_ACCESS_POLICY' THEN 'ROW ACCESS POLICY'
            WHEN QUERY_TYPE = 'DROP_ROW_ACCESS_POLICY' THEN 'ROW ACCESS POLICY'
            -- MASKING POLICY
            WHEN QUERY_TYPE = 'CREATE_MASKING_POLICY' THEN 'MASKING POLICY'
            WHEN QUERY_TYPE = 'ALTER_TABLE_MODIFY_COLUMN' THEN 'MASKING POLICY'
            WHEN QUERY_TYPE = 'DROP_MASKING_POLICY' THEN 'MASKING POLICY'
            
            ------ IDENTIFIABLE THROUGH QUERY_TEXT ------
            -- ACCOUNT 
            WHEN QUERY_TEXT ILIKE 'CREATE ACCOUNT%' THEN 'ACCOUNT'
            WHEN QUERY_TEXT ILIKE 'ALTER ACCOUNT%' THEN 'ACCOUNT'
            WHEN QUERY_TEXT ILIKE 'DROP ACCOUNT%' THEN 'ACCOUNT'
            -- MANAGED ACCOUNT
            WHEN QUERY_TEXT ILIKE 'CREATE MANAGED ACCOUNT%' THEN 'MANAGED ACCOUNT' 
            WHEN QUERY_TEXT ILIKE 'DROP MANAGED ACCOUNT%' THEN 'MANAGED ACCOUNT'
            -- DATA SHARING
            WHEN QUERY_TEXT ILIKE 'CREATE SHARE%' THEN 'DATA SHARE'
            WHEN QUERY_TEXT ILIKE 'CREATE OR REPLACE SHARE%' THEN 'DATA SHARE'
            WHEN QUERY_TEXT ILIKE 'ALTER SHARE%' THEN 'DATA SHARE'
            WHEN QUERY_TEXT ILIKE 'DROP SHARE%' THEN 'DATA SHARE'
            -- COMPUTE WAREHOUSE
            WHEN QUERY_TEXT ILIKE 'CREATE WAREHOUSE%' THEN 'WAREHOUSE'
            WHEN QUERY_TEXT ILIKE 'CREATE OR REPLACE WAREHOUSE%' THEN 'WAREHOUSE'
            WHEN QUERY_TEXT ILIKE 'CREATE OR ALTER WAREHOUSE%' THEN 'WAREHOUSE'
            WHEN QUERY_TEXT ILIKE 'ALTER WAREHOUSE%' THEN 'WAREHOUSE'
            WHEN QUERY_TEXT ILIKE 'DROP WAREHOUSE%' THEN 'WAREHOUSE'
            -- RESOURCE MONITOR
            WHEN QUERY_TEXT ILIKE 'CREATE RESOURCE MONITOR%' THEN 'RESOURCE MONITOR'
            WHEN QUERY_TEXT ILIKE 'CREATE OR REPLACE RESOURCE MONITOR%' THEN 'RESOURCE MONITOR'
            WHEN QUERY_TEXT ILIKE 'CREATE OR ALTER RESOURCE MONITOR%' THEN 'RESOURCE MONITOR'
            WHEN QUERY_TEXT ILIKE 'ALTER RESOURCE MONITOR%' THEN 'RESOURCE MONITOR'
            WHEN QUERY_TEXT ILIKE 'DROP RESOURCE MONITOR%' THEN 'RESOURCE MONITOR'
            -- INTEGRATIONS 
            WHEN QUERY_TEXT ILIKE 'CREATE EXTERNAL ACCESS INTEGRATION%' THEN 'INTEGRATION'
            WHEN QUERY_TEXT ILIKE 'CREATE OR REPLACE EXTERNAL ACCESS INTEGRATION%' THEN 'INTEGRATION'
            WHEN QUERY_TEXT ILIKE 'CREATE API INTEGRATION%' THEN 'INTEGRATION'
            WHEN QUERY_TEXT ILIKE 'CREATE OR REPLACE API INTEGRATION%' THEN 'INTEGRATION'
            WHEN QUERY_TEXT ILIKE 'CREATE CATALOG INTEGRATION%' THEN 'INTEGRATION'
            WHEN QUERY_TEXT ILIKE 'CREATE OR REPLACE CATALOG INTEGRATION%' THEN 'INTEGRATION'
            WHEN QUERY_TEXT ILIKE 'CREATE NOTIFICATION INTEGRATION%' THEN 'INTEGRATION'
            WHEN QUERY_TEXT ILIKE 'CREATE OR REPLACE NOTIFICATION INTEGRATION%' THEN 'INTEGRATION'
            WHEN QUERY_TEXT ILIKE 'CREATE SECURITY INTEGRATION%' THEN 'INTEGRATION'
            WHEN QUERY_TEXT ILIKE 'CREATE OR REPLACE SECURITY INTEGRATION%' THEN 'INTEGRATION'
            WHEN QUERY_TEXT ILIKE 'CREATE STORAGE INTEGRATION%' THEN 'INTEGRATION'
            WHEN QUERY_TEXT ILIKE 'CREATE OR REPLACE STORAGE INTEGRATION%' THEN 'INTEGRATION'
            WHEN QUERY_TEXT ILIKE 'ALTER EXTERNAL ACCESS INTEGRATION%' THEN 'INTEGRATION'
            WHEN QUERY_TEXT ILIKE 'ALTER API INTEGRATION%' THEN 'INTEGRATION'
            WHEN QUERY_TEXT ILIKE 'ALTER CATALOG INTEGRATION%' THEN 'INTEGRATION'
            WHEN QUERY_TEXT ILIKE 'ALTER NOTIFICATION INTEGRATION%' THEN 'INTEGRATION'
            WHEN QUERY_TEXT ILIKE 'ALTER SECURITY INTEGRATION%' THEN 'INTEGRATION'
            WHEN QUERY_TEXT ILIKE 'ALTER STORAGE INTEGRATION%' THEN 'INTEGRATION'
            WHEN QUERY_TEXT ILIKE 'DROP INTEGRATION%' THEN 'INTEGRATION'
        END AS QUERY_DOMAIN
    FROM 
        SNOWFLAKE_METADATA_RESULT
)

SELECT 
    QUERY_DOMAIN,
    MAX(START_TIME) AS LATEST_QUERY_DATETIME,
    COUNT(*) AS QUERY_COUNT
FROM 
    SNOWFLAKE_METADATA_CLASSIFIED
WHERE 1=1
    AND QUERY_DOMAIN IS NOT NULL
GROUP BY 
    QUERY_DOMAIN;


CREATE OR REPLACE VIEW MONITORING_ASSESSMENT_DB.ASSESSMENT.V_USER AS
SELECT
    QUERY_ID,
    START_TIME,
    USER_NAME,
    ROLE_NAME,
    QUERY_TEXT
FROM 
    SNOWFLAKE.ACCOUNT_USAGE.QUERY_HISTORY
WHERE 1=1 
    AND START_TIME >= DATEADD(DAY, -90, CURRENT_TIMESTAMP())
    AND QUERY_TYPE NOT IN ('SELECT','INSERT','UPDATE','DELETE','MERGE','SHOW','USE','DESCRIBE')
    AND EXECUTION_STATUS = 'SUCCESS'
    AND USER_NAME NOT IN ('SYSTEM')
    AND ROLE_NAME NOT IN ('SNOWFLAKE')
    AND QUERY_TYPE IN ('CREATE_USER', 'ALTER_USER' ,'DROP_USER')
QUALIFY ROW_NUMBER() OVER (PARTITION BY QUERY_ID ORDER BY START_TIME) = 1;


CREATE OR REPLACE VIEW MONITORING_ASSESSMENT_DB.ASSESSMENT.V_ROLE AS
SELECT
    QUERY_ID,
    START_TIME,
    USER_NAME,
    ROLE_NAME,
    QUERY_TEXT
FROM 
    SNOWFLAKE.ACCOUNT_USAGE.QUERY_HISTORY
WHERE 1=1 
    AND START_TIME >= DATEADD(DAY, -90, CURRENT_TIMESTAMP())
    AND QUERY_TYPE NOT IN ('SELECT','INSERT','UPDATE','DELETE','MERGE','SHOW','USE','DESCRIBE')
    AND EXECUTION_STATUS = 'SUCCESS'
    AND USER_NAME NOT IN ('SYSTEM')
    AND ROLE_NAME NOT IN ('SNOWFLAKE')
    AND QUERY_TYPE IN ('CREATE_ROLE', 'ALTER_ROLE' ,'DROP_ROLE')
QUALIFY ROW_NUMBER() OVER (PARTITION BY QUERY_ID ORDER BY START_TIME) = 1;


CREATE OR REPLACE VIEW MONITORING_ASSESSMENT_DB.ASSESSMENT.V_GRANT_REVOKE AS
SELECT
    QUERY_ID,
    START_TIME,
    USER_NAME,
    ROLE_NAME,
    QUERY_TEXT
FROM 
    SNOWFLAKE.ACCOUNT_USAGE.QUERY_HISTORY
WHERE 1=1 
    AND START_TIME >= DATEADD(DAY, -90, CURRENT_TIMESTAMP())
    AND QUERY_TYPE NOT IN ('SELECT','INSERT','UPDATE','DELETE','MERGE','SHOW','USE','DESCRIBE')
    AND EXECUTION_STATUS = 'SUCCESS'
    AND USER_NAME NOT IN ('SYSTEM')
    AND ROLE_NAME NOT IN ('SNOWFLAKE')
    AND QUERY_TYPE IN ('GRANT', 'REVOKE')
QUALIFY ROW_NUMBER() OVER (PARTITION BY QUERY_ID ORDER BY START_TIME) = 1;


CREATE OR REPLACE VIEW MONITORING_ASSESSMENT_DB.ASSESSMENT.V_NETWORK_POLICY AS
SELECT
    QUERY_ID,
    START_TIME,
    USER_NAME,
    ROLE_NAME,
    QUERY_TEXT
FROM 
    SNOWFLAKE.ACCOUNT_USAGE.QUERY_HISTORY
WHERE 1=1 
    AND START_TIME >= DATEADD(DAY, -90, CURRENT_TIMESTAMP())
    AND QUERY_TYPE NOT IN ('SELECT','INSERT','UPDATE','DELETE','MERGE','SHOW','USE','DESCRIBE')
    AND EXECUTION_STATUS = 'SUCCESS'
    AND USER_NAME NOT IN ('SYSTEM')
    AND ROLE_NAME NOT IN ('SNOWFLAKE')
    AND QUERY_TYPE IN ('CREATE_NETWORK_POLICY', 'ALTER_NETWORK_POLICY', 'DROP_NETWORK_POLICY')
QUALIFY ROW_NUMBER() OVER (PARTITION BY QUERY_ID ORDER BY START_TIME) = 1;


CREATE OR REPLACE VIEW MONITORING_ASSESSMENT_DB.ASSESSMENT.V_ROW_ACCESS_POLICY AS
SELECT
    QUERY_ID,
    START_TIME,
    USER_NAME,
    ROLE_NAME,
    QUERY_TEXT
FROM 
    SNOWFLAKE.ACCOUNT_USAGE.QUERY_HISTORY
WHERE 1=1 
    AND START_TIME >= DATEADD(DAY, -90, CURRENT_TIMESTAMP())
    AND QUERY_TYPE NOT IN ('SELECT','INSERT','UPDATE','DELETE','MERGE','SHOW','USE','DESCRIBE')
    AND EXECUTION_STATUS = 'SUCCESS'
    AND USER_NAME NOT IN ('SYSTEM')
    AND ROLE_NAME NOT IN ('SNOWFLAKE')
    AND QUERY_TYPE IN ('CREATE_ROW_ACCESS_POLICY', 'ALTER_TABLE_MANAGE_ROW_ACCESS_POLICY', 'DROP_ROW_ACCESS_POLICY')
QUALIFY ROW_NUMBER() OVER (PARTITION BY QUERY_ID ORDER BY START_TIME) = 1;


CREATE OR REPLACE VIEW MONITORING_ASSESSMENT_DB.ASSESSMENT.V_MASKING_POLICY AS
SELECT
    QUERY_ID,
    START_TIME,
    USER_NAME,
    ROLE_NAME,
    QUERY_TEXT
FROM 
    SNOWFLAKE.ACCOUNT_USAGE.QUERY_HISTORY
WHERE 1=1 
    AND START_TIME >= DATEADD(DAY, -90, CURRENT_TIMESTAMP())
    AND QUERY_TYPE NOT IN ('SELECT','INSERT','UPDATE','DELETE','MERGE','SHOW','USE','DESCRIBE')
    AND EXECUTION_STATUS = 'SUCCESS'
    AND USER_NAME NOT IN ('SYSTEM')
    AND ROLE_NAME NOT IN ('SNOWFLAKE')
    AND QUERY_TYPE IN ('CREATE_MASKING_POLICY', 'ALTER_TABLE_MODIFY_COLUMN', 'DROP_MASKING_POLICY')
QUALIFY ROW_NUMBER() OVER (PARTITION BY QUERY_ID ORDER BY START_TIME) = 1;


CREATE OR REPLACE VIEW MONITORING_ASSESSMENT_DB.ASSESSMENT.V_ACCOUNT AS
SELECT
    QUERY_ID,
    START_TIME,
    USER_NAME,
    ROLE_NAME,
    QUERY_TEXT
FROM 
    SNOWFLAKE.ACCOUNT_USAGE.QUERY_HISTORY
WHERE 1=1 
    AND START_TIME >= DATEADD(DAY, -90, CURRENT_TIMESTAMP())
    AND QUERY_TYPE NOT IN ('SELECT','INSERT','UPDATE','DELETE','MERGE','SHOW','USE','DESCRIBE')
    AND EXECUTION_STATUS = 'SUCCESS'
    AND USER_NAME NOT IN ('SYSTEM')
    AND ROLE_NAME NOT IN ('SNOWFLAKE')
    AND (
        QUERY_TEXT ILIKE 'CREATE ACCOUNT%' OR
        QUERY_TEXT ILIKE 'ALTER ACCOUNT%' OR
        QUERY_TEXT ILIKE 'DROP ACCOUNT%' 
    )
QUALIFY ROW_NUMBER() OVER (PARTITION BY QUERY_ID ORDER BY START_TIME) = 1;


CREATE OR REPLACE VIEW MONITORING_ASSESSMENT_DB.ASSESSMENT.V_MANAGED_ACCOUNT AS
SELECT
    QUERY_ID,
    START_TIME,
    USER_NAME,
    ROLE_NAME,
    QUERY_TEXT
FROM 
    SNOWFLAKE.ACCOUNT_USAGE.QUERY_HISTORY
WHERE 1=1 
    AND START_TIME >= DATEADD(DAY, -90, CURRENT_TIMESTAMP())
    AND QUERY_TYPE NOT IN ('SELECT','INSERT','UPDATE','DELETE','MERGE','SHOW','USE','DESCRIBE')
    AND EXECUTION_STATUS = 'SUCCESS'
    AND USER_NAME NOT IN ('SYSTEM')
    AND ROLE_NAME NOT IN ('SNOWFLAKE')
    AND (
        QUERY_TEXT ILIKE 'CREATE MANAGED ACCOUNT%' OR
        QUERY_TEXT ILIKE 'DROP MANAGED ACCOUNT%'
    )
QUALIFY ROW_NUMBER() OVER (PARTITION BY QUERY_ID ORDER BY START_TIME) = 1;


CREATE OR REPLACE VIEW MONITORING_ASSESSMENT_DB.ASSESSMENT.V_DATA_SHARE AS
SELECT
    QUERY_ID,
    START_TIME,
    USER_NAME,
    ROLE_NAME,
    QUERY_TEXT
FROM 
    SNOWFLAKE.ACCOUNT_USAGE.QUERY_HISTORY
WHERE 1=1 
    AND START_TIME >= DATEADD(DAY, -90, CURRENT_TIMESTAMP())
    AND QUERY_TYPE NOT IN ('SELECT','INSERT','UPDATE','DELETE','MERGE','SHOW','USE','DESCRIBE')
    AND EXECUTION_STATUS = 'SUCCESS'
    AND USER_NAME NOT IN ('SYSTEM')
    AND ROLE_NAME NOT IN ('SNOWFLAKE')
    AND (
        QUERY_TEXT ILIKE 'CREATE SHARE%' OR
        QUERY_TEXT ILIKE 'CREATE OR REPLACE SHARE%' OR
        QUERY_TEXT ILIKE 'ALTER SHARE%' OR
        QUERY_TEXT ILIKE 'DROP SHARE%' 
    )
QUALIFY ROW_NUMBER() OVER (PARTITION BY QUERY_ID ORDER BY START_TIME) = 1;


CREATE OR REPLACE VIEW MONITORING_ASSESSMENT_DB.ASSESSMENT.V_WAREHOUSE AS
SELECT
    QUERY_ID,
    START_TIME,
    USER_NAME,
    ROLE_NAME,
    QUERY_TEXT
FROM 
    SNOWFLAKE.ACCOUNT_USAGE.QUERY_HISTORY
WHERE 1=1 
    AND START_TIME >= DATEADD(DAY, -90, CURRENT_TIMESTAMP())
    AND QUERY_TYPE NOT IN ('SELECT','INSERT','UPDATE','DELETE','MERGE','SHOW','USE','DESCRIBE')
    AND EXECUTION_STATUS = 'SUCCESS'
    AND USER_NAME NOT IN ('SYSTEM')
    AND ROLE_NAME NOT IN ('SNOWFLAKE')
    AND (
        QUERY_TEXT ILIKE 'CREATE WAREHOUSE%' OR
        QUERY_TEXT ILIKE 'CREATE OR REPLACE WAREHOUSE%' OR
        QUERY_TEXT ILIKE 'CREATE OR ALTER WAREHOUSE%' OR
        QUERY_TEXT ILIKE 'ALTER WAREHOUSE%' OR
        QUERY_TEXT ILIKE 'DROP WAREHOUSE%' 
    )
QUALIFY ROW_NUMBER() OVER (PARTITION BY QUERY_ID ORDER BY START_TIME) = 1;


CREATE OR REPLACE VIEW MONITORING_ASSESSMENT_DB.ASSESSMENT.V_RESOURCE_MONITOR AS
SELECT
    QUERY_ID,
    START_TIME,
    USER_NAME,
    ROLE_NAME,
    QUERY_TEXT
FROM 
    SNOWFLAKE.ACCOUNT_USAGE.QUERY_HISTORY
WHERE 1=1 
    AND START_TIME >= DATEADD(DAY, -90, CURRENT_TIMESTAMP())
    AND QUERY_TYPE NOT IN ('SELECT','INSERT','UPDATE','DELETE','MERGE','SHOW','USE','DESCRIBE')
    AND EXECUTION_STATUS = 'SUCCESS'
    AND USER_NAME NOT IN ('SYSTEM')
    AND ROLE_NAME NOT IN ('SNOWFLAKE')
    AND (
        QUERY_TEXT ILIKE 'CREATE RESOURCE MONITOR%' OR
        QUERY_TEXT ILIKE 'CREATE OR REPLACE RESOURCE MONITOR%' OR
        QUERY_TEXT ILIKE 'CREATE OR ALTER RESOURCE MONITOR%' OR
        QUERY_TEXT ILIKE 'ALTER RESOURCE MONITOR%' OR
        QUERY_TEXT ILIKE 'DROP RESOURCE MONITOR%' 
    )
QUALIFY ROW_NUMBER() OVER (PARTITION BY QUERY_ID ORDER BY START_TIME) = 1;


CREATE OR REPLACE VIEW MONITORING_ASSESSMENT_DB.ASSESSMENT.V_INTEGRATION AS
SELECT
    QUERY_ID,
    START_TIME,
    USER_NAME,
    ROLE_NAME,
    QUERY_TEXT
FROM 
    SNOWFLAKE.ACCOUNT_USAGE.QUERY_HISTORY
WHERE 1=1 
    AND START_TIME >= DATEADD(DAY, -90, CURRENT_TIMESTAMP())
    AND QUERY_TYPE NOT IN ('SELECT','INSERT','UPDATE','DELETE','MERGE','SHOW','USE','DESCRIBE')
    AND EXECUTION_STATUS = 'SUCCESS'
    AND USER_NAME NOT IN ('SYSTEM')
    AND ROLE_NAME NOT IN ('SNOWFLAKE')
    AND (
        QUERY_TEXT ILIKE 'CREATE EXTERNAL ACCESS INTEGRATION%' OR
        QUERY_TEXT ILIKE 'CREATE OR REPLACE EXTERNAL ACCESS INTEGRATION%' OR
        QUERY_TEXT ILIKE 'CREATE API INTEGRATION%' OR
        QUERY_TEXT ILIKE 'CREATE OR REPLACE API INTEGRATION%' OR
        QUERY_TEXT ILIKE 'CREATE CATALOG INTEGRATION%' OR
        QUERY_TEXT ILIKE 'CREATE OR REPLACE CATALOG INTEGRATION%' OR
        QUERY_TEXT ILIKE 'CREATE NOTIFICATION INTEGRATION%' OR
        QUERY_TEXT ILIKE 'CREATE OR REPLACE NOTIFICATION INTEGRATION%' OR
        QUERY_TEXT ILIKE 'CREATE SECURITY INTEGRATION%' OR
        QUERY_TEXT ILIKE 'CREATE OR REPLACE SECURITY INTEGRATION%' OR
        QUERY_TEXT ILIKE 'CREATE STORAGE INTEGRATION%' OR
        QUERY_TEXT ILIKE 'CREATE OR REPLACE STORAGE INTEGRATION%' OR
        QUERY_TEXT ILIKE 'ALTER EXTERNAL ACCESS INTEGRATION%' OR
        QUERY_TEXT ILIKE 'ALTER API INTEGRATION%' OR
        QUERY_TEXT ILIKE 'ALTER CATALOG INTEGRATION%' OR
        QUERY_TEXT ILIKE 'ALTER NOTIFICATION INTEGRATION%' OR
        QUERY_TEXT ILIKE 'ALTER SECURITY INTEGRATION%' OR
        QUERY_TEXT ILIKE 'ALTER STORAGE INTEGRATION%' OR
        QUERY_TEXT ILIKE 'DROP INTEGRATION%'
    )
QUALIFY ROW_NUMBER() OVER (PARTITION BY QUERY_ID ORDER BY START_TIME) = 1;