
USE ROLE MONITORING_ASSESSMENT_ROLE;
USE SECONDARY ROLES NONE;
USE WAREHOUSE MONITORING_ASSESSMENT_WH;

CREATE OR REPLACE TABLE MONITORING_ASSESSMENT_DB.ASSESSMENT.MONITORING_RULES (
    RULE_ID INT AUTOINCREMENT START 1 INCREMENT 1 ORDER PRIMARY KEY,
    RULE_DOMAIN VARCHAR(16777216),
    RULE_DESCRIPTION VARCHAR(16777216),
    RULE_OBJECT VARCHAR(16777216),
	ENABLED BOOLEAN
);


CREATE OR REPLACE TABLE MONITORING_ASSESSMENT_DB.ASSESSMENT.MONITORING_EVENTS (
    EVENT_ID INT AUTOINCREMENT START 1 INCREMENT 1 ORDER PRIMARY KEY,
    RULE_ID INT, 
    QUERY_ID VARCHAR(16777216),
    EVENT_TIME VARCHAR(16777216),
    USER_NAME VARCHAR(16777216),
    ROLE_NAME VARCHAR(16777216),
    QUERY_TEXT VARCHAR(16777216),
    CORTEX_RESPONSE VARIANT,
    CORTEX_SUMMARY VARCHAR(16777216),
    LOAD_DATETIME TIMESTAMP_NTZ(9) DEFAULT CURRENT_TIMESTAMP()
);