
USE ROLE MONITORING_ASSESSMENT_ROLE;
USE SECONDARY ROLES NONE;
USE WAREHOUSE MONITORING_ASSESSMENT_WH;

INSERT INTO MONITORING_ASSESSMENT_DB.ASSESSMENT.MONITORING_RULES (
    RULE_DOMAIN,
    RULE_DESCRIPTION,
    RULE_OBJECT,
    ENABLED
) VALUES 
('USER','User created, modified, or dropped','MONITORING_ASSESSMENT_DB.ASSESSMENT.V_USER',FALSE),
('ROLE','Role created, modified, or dropped','MONITORING_ASSESSMENT_DB.ASSESSMENT.V_ROLE',FALSE),
('GRANT AND REVOKE','Privileges granted or revoked, inclusive of both user and roles','MONITORING_ASSESSMENT_DB.ASSESSMENT.V_GRANT_REVOKE',FALSE),
('NETWORK POLICY','Network policy created, modified, or dropped','MONITORING_ASSESSMENT_DB.ASSESSMENT.V_NETWORK_POLICY',FALSE),
('ROW ACCESS POLICY','Row access policy created, applied, or dropped','MONITORING_ASSESSMENT_DB.ASSESSMENT.V_ROW_ACCESS_POLICY',FALSE),
('MASKING POLICY','Masking policy created, applied, or dropped','MONITORING_ASSESSMENT_DB.ASSESSMENT.V_MASKING_POLICY',FALSE),
('ACCOUNT','Account created, modified, or dropped','MONITORING_ASSESSMENT_DB.ASSESSMENT.V_ACCOUNT',FALSE),
('MANAGED ACCOUNT','Managed account created, modified, or dropped','MONITORING_ASSESSMENT_DB.ASSESSMENT.V_MANAGED_ACCOUNT',FALSE),
('DATA SHARE','Data share created, modified, or dropped','MONITORING_ASSESSMENT_DB.ASSESSMENT.V_DATA_SHARE',FALSE),
('WAREHOUSE','Compute warehouse created, modified, or dropped','MONITORING_ASSESSMENT_DB.ASSESSMENT.V_WAREHOUSE',FALSE),
('RESOURCE MONITOR','Resource monitor created, modified, or dropped','MONITORING_ASSESSMENT_DB.ASSESSMENT.V_RESOURCE_MONITOR',FALSE),
('INTEGRATION','Integration created, modified, or dropped','MONITORING_ASSESSMENT_DB.ASSESSMENT.V_INTEGRATION',FALSE);