
USE ROLE ACCOUNTADMIN;
USE SECONDARY ROLES NONE;

-- ----------------------------------------
-- DROP ROLE, GRANTS, AND WAREHOUSE 
REVOKE IMPORTED PRIVILEGES ON DATABASE SNOWFLAKE FROM ROLE MONITORING_ASSESSMENT_ROLE;
REVOKE DATABASE ROLE SNOWFLAKE.GOVERNANCE_VIEWER FROM ROLE MONITORING_ASSESSMENT_ROLE;
REVOKE DATABASE ROLE SNOWFLAKE.SECURITY_VIEWER FROM ROLE MONITORING_ASSESSMENT_ROLE;
REVOKE DATABASE ROLE SNOWFLAKE.USAGE_VIEWER FROM ROLE MONITORING_ASSESSMENT_ROLE;

DROP ROLE IF EXISTS MONITORING_ASSESSMENT_ROLE;
DROP WAREHOUSE IF EXISTS MONITORING_ASSESSMENT_WH;

-- ----------------------------------------
-- STREAMLIT APP 
DROP STREAMLIT IF EXISTS MONITORING_ASSESSMENT_DB.ASSESSMENT.MONITORING_ASSESSMENT_APP;

-- ----------------------------------------
-- DROP DATABASE AND OBJECTS
USE ROLE SYSADMIN;
USE SECONDARY ROLES NONE;

DROP DATABASE IF EXISTS MONITORING_ASSESSMENT_DB;